### ISSUE TITLE
Página de inicio  Imagen de fondo para listas de especies: 

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/species_checklist_frontend#11]
Página de inicio	" Imagen de fondo para listas de especies: 

https://s3.amazonaws.com/sib-resources/images/listas+de+especies/jpg/murcielago-opt.jpg 

Créditos: Mamíferos de Colombia - Enlace: https://www.flickr.com/photos/154330806@N06/36177125034 - Licencia: CC BY-NC 2.0"

**Comment by RicardoOrtizG** [comment]
Se cumple con el contenido y los créditos
