### ISSUE TITLE
Página de inicio	Ajustar los slides del banner Listas de referencia, contenidos, logo y mockups en el correo.

### ISSUE THREAD

**Issue by jag2kn** [SIB-Colombia/species_checklist_frontend#12]
Página de inicio	Ajustar los slides del banner Listas de referencia, contenidos, logo y mockups en el correo.

**Comment by RicardoOrtizG** [comment]
Aparentemente se cumple con los logos, y funcionamiento. Respecto al contenido @javiesgm por favor contrastar con los muckups si se escapa algo.
