### ISSUE TITLE
LISTAS DE ESPECIES | FILTRO LATERAL | Filtro por ubicación 'Departamento' sin resultados

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/species_checklist_frontend#40]
El filtro por departamento no genera ningun resultado. Este debería apuntar a la extensión 'occurrence' del Core 'taxon'

**Comment by iraidamercedes** [comment]
Se cierra por se issue igual a otro documentado y se agrupa en issue #39
