### ISSUE TITLE
LISTAS DE ESPECIES | FILTRO LATERAL | Filtro por ubicación 'Municipio' sin resultados

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/species_checklist_frontend#41]
El filtro de municipio no genera ningún resultado. Este debería estar conectado a la extensión 'occurrence' del core 'taxon'.

**Comment by iraidamercedes** [comment]
Se cierra por se issue igual a otro documentado y se agrupa en issue #39
