### ISSUE TITLE
LISTAS DE ESPECIES | FILTRO LATERAL | Filtro por ubicación 'localidad' sin resultados

### ISSUE THREAD

**Issue by RicardoOrtizG** [SIB-Colombia/species_checklist_frontend#42]
Este filtro no genera ningún resultado. Este filtro debería estar conectado al elemento 'locality' de la extensión 'occurrence' del core 'taxon'. 

Pregunta: ¿Podría conectarse también al elemento 'locality' de la extensión 'species distribution'?. @leobuitrago

**Comment by iraidamercedes** [comment]
Se cierra por se issue igual a otro documentado y se agrupa en issue #39
