### ISSUE TITLE
Agregar slider promocional editable en el home

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/species_checklist_frontend#7]
@jag2kn la idea es agregar un slider como el de "comunidad" que aparece en la página de inicio del Catálogo de la biodiversidad. Algo que nos permita administrar estos contenidos fácilmente. 

Adjunto mockup: 
PDF --> 
[HOME-Listas-Vnov.pdf](https://github.com/SIB-Colombia/species_checklist_frontend/files/1518344/HOME-Listas-Vnov.pdf)

**Comment by jag2kn** [comment]
@javiesgm en proceso

**Comment by RicardoOrtizG** [comment]
Se cumple con el contenido y la funcionalidad del slider. Pendiente de verificar la facilidad de la administración de los contenidos del slider @javiesgm
