### ISSUE TITLE
Acerca de y condiciones de uso

### ISSUE THREAD

**Issue by javiesgm** [SIB-Colombia/species_checklist_frontend#8]
Aquí están los mockups de las páginas Sobre Listas de Especies y Condiciones de Uso:
https://drive.google.com/file/d/1ePQeCh1bAYIXz8Z40wLW1HWGW-6ntdre/view?usp=sharing

Condiciones de uso (Documento con textos y enlaces): 
https://docs.google.com/document/d/1MqU41SnrhD02R2SvoDh79Cu6u2_07QPAl1bjZVotzgM/edit?usp=sharing

Sobre el portal (Documento con textos y enlaces): 
https://docs.google.com/document/d/11vlfYdCYKMoXbkJqUV80zksOnQLB_-pr8Jc0Bkinxiw/edit?usp=sharing

**Comment by RicardoOrtizG** [comment]
Comentado en el Issue #13 y Issue #15
